---
- name: Load the OS specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: Install the logrotate package 
  package: 
    name: '{{ logrotate_pkgs }}'
    state: present

- name: Load logrotate config file
  template: 
    src: logrotate.conf.j2
    dest: /etc/logrotate.conf
    owner: root
    group: root
    mode: 0644

